version: "3"
services:
  # server:
  #   build: .
  #   restart: on-failure
  #   # stdin_open: true
  #   # tty: true
  #   volumes:
  #     - .:/app
  #   env_file: .env
  #   depends_on:
  #     - database
  #   ports:
  #     - "8080:8080"
    # platform: "linux/amd64"
    # extra_hosts:
    #   - "host.docker.internal:172.27.0.3"  
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: